# Imports

```{python}
import pandas as pd

pd.options.mode.copy_on_write = True
```

# Dataset

```{python}
counties = pd.read_csv("data/us_counties_data.csv")
counties
```

```{python}
area_df = counties[["county", "area_sq_miles", "pop_20"]]
area_df
```

# Creating New Variables

```{python}
# New var with sq km
area_df["area_sq_km"] = area_df["area_sq_miles"] * 2.59
# New var with area in hectares
area_df["area_hectares"] = area_df["area_sq_km"] * 100
area_df
```

# Practice Q: Area in Acres

Using the "area_df" dataset, creat a new colum
called "area_acres" by multiplying the "area_sq_miles"
variable by 640. Store the result into "area_df" and display the Data Frame.

```{python}
# New var with area in acres
area_df["area_acres"] = area_df["area_sq_miles"] * 640
area_df
```

#Modifying Existing Variables

```{python}
area_df["area_sq_km"] = area_df["area_sq_km"].round(2)
area_df
```

# Practice Q: Rounding area_acres

Using the area_df dataset, round the area_acres variable to one decimal place. Update the data frame and display it.

```{python}
area_df["area_acres"] = area_df["area_acres"].round(1)
area_df
```

# Calculating with Multiple Variables

```{python}
area_df["pop_per_sq_km"] = (area_df["pop_20"] / area_df["area_sq_km"]).round(1)
area_df = area_df.sort_values(by = "pop_per_sq_km", ascending = False)
area_df
```

# Practice Q: Foreing Born Percentage

Use the counties dataset to calculate the percentage of foreing-born residents in each county. (Remember to multiply your proportion bt 100). The variable foreing_born_num shows the number of foreign-born residents and pop_20 shows the total population. Which two counties have the highest percentage of foreign-born residents?

```{python}
counties_2_df = counties[["county", "foreign_born_num", "pop_20"]]
counties_2_df["foreign_born_per"] = (counties_2_df["foreign_born_num"] / counties_2_df["pop_20"] * 100).round(2)
counties_2_df = counties_2_df.sort_values(by = "foreign_born_per", ascending = False)
counties_2_df
```

The two counties with the highest percentage of foreing-born residents are Miami-Dade, Florida and Queens New York.

# Creating Boolean Variables

```{python}
counties
```

```{python}
changes_df = counties[["county", "pop_change_2010_2020", "pct_emp_change_2010_2021"]]
changes_df
```

```{python}
changes_df["pop_increase"] = changes_df["pop_change_2010_2020"] > 0
changes_df["emp_increase"] = changes_df["pct_emp_change_2010_2021"] > 0
changes_df
```

```{python}
# These two queries are equivalent
changes_df.query("pop_increase == True & emp_increase == False")
changes_df.query("pop_increase & ~(emp_increase)")
```

# Practice Q: Categorize Counties by Foreing-Born Population

Create a Boolean variable 'foreign_born_pct_30' that is true if the percentage is greater than 30%.

When you are done, query the DataFrame to show only counties where 'foreign_born_pct_30' is True. You should get 24 rows.

```{python}
counties_2_df["foreing_born_pct_30"] = counties_2_df["foreign_born_per"] > 30
counties_2_df
```

```{python}
# These two queries are equivalent
counties_2_df.query("foreing_born_pct_30 == True")
```

# Copy on Write Warning

```{python}
pd.options.mode.copy_on_write = True

counties_mini = counties[["county", "area_sq_miles"]]

counties_mini["area_sq_miles"] = counties_mini["area_sq_miles"].round(2)

counties_mini
```





